"""initial

Revision ID: 2254a15bcf3b
Revises: 
Create Date: 2026-08-14 08:34:40.484625
"""
from alembic import op
import sqlalchemy as sa


revision = '2254a15bcf3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION', 'READY', 'LIVE', 'CLOSED', 'RESULTS_PUBLISHED', name='electionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('COMMISSIONER', 'CANDIDATE', name='role'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('hall_of_residence', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('ELECTION', 'CANDIDATE', 'VOTER', 'RESULT', 'SYSTEM', name='activitytype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('election_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_election_id'), 'positions', ['election_id'], unique=False)
    op.create_table('voters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('voter_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hall', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ELIGIBLE', 'VOTED', 'INVALID', name='voterstatus'), nullable=False),
    sa.Column('has_voted', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'voter_id', name='uq_voter_election_voterid')
    )
    op.create_index(op.f('ix_voters_election_id'), 'voters', ['election_id'], unique=False)
    op.create_index(op.f('ix_voters_voter_id'), 'voters', ['voter_id'], unique=False)
    op.create_table('ballots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('voter_db_id', sa.String(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['voter_db_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'voter_db_id', name='uq_ballot_election_voter'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_ballots_election_id'), 'ballots', ['election_id'], unique=False)
    op.create_index(op.f('ix_ballots_voter_db_id'), 'ballots', ['voter_db_id'], unique=False)
    op.create_table('candidate_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('hall_of_residence', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('manifesto', sa.Text(), nullable=False),
    sa.Column('running_mate', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='candidatestatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'student_id', name='uq_candidate_election_student')
    )
    op.create_index(op.f('ix_candidate_applications_election_id'), 'candidate_applications', ['election_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_position_id'), 'candidate_applications', ['position_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('voter_db_id', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['voter_db_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_election_id'), 'otp_challenges', ['election_id'], unique=False)
    op.create_index(op.f('ix_otp_challenges_voter_db_id'), 'otp_challenges', ['voter_db_id'], unique=False)
    op.create_table('voting_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('voter_db_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['voter_db_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_voting_sessions_election_id'), 'voting_sessions', ['election_id'], unique=False)
    op.create_index(op.f('ix_voting_sessions_voter_db_id'), 'voting_sessions', ['voter_db_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ballot_id', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_applications.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballot_id', 'position_id', name='uq_vote_ballot_position')
    )
    op.create_index(op.f('ix_votes_ballot_id'), 'votes', ['ballot_id'], unique=False)
    op.create_index(op.f('ix_votes_candidate_id'), 'votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_votes_election_id'), 'votes', ['election_id'], unique=False)
    op.create_index(op.f('ix_votes_position_id'), 'votes', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_position_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_election_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_candidate_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_ballot_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_voting_sessions_voter_db_id'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_election_id'), table_name='voting_sessions')
    op.drop_table('voting_sessions')
    op.drop_index(op.f('ix_otp_challenges_voter_db_id'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_election_id'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_candidate_applications_position_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_election_id'), table_name='candidate_applications')
    op.drop_table('candidate_applications')
    op.drop_index(op.f('ix_ballots_voter_db_id'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_election_id'), table_name='ballots')
    op.drop_table('ballots')
    op.drop_index(op.f('ix_voters_voter_id'), table_name='voters')
    op.drop_index(op.f('ix_voters_election_id'), table_name='voters')
    op.drop_table('voters')
    op.drop_index(op.f('ix_positions_election_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('elections')
    # ### end Alembic commands ###
